name: ai-revision
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to revise'
        required: true
        type: string
        default: 'main'
      file_names:
        description: 'File names to revise'
        required: false
        type: string
        default: ''
      model:
        description: 'Language model'
        required: true
        type: string
        default: 'text-davinci-003'
      branch_name:
        description: 'Output branch'
        required: true
        type: string
        default: 'ai-revision-davinci'

jobs:
  ai-revise:
    name: AI Revise
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with: 
          ref: ${{ inputs.branch }} 
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ci/cache
          key: ci-cache-${{ github.ref }}
          restore-keys: |
            ci-cache-${{ env.DEFAULT_BRANCH_REF }}-${{ hashFiles('build/environment.yml') }}
      - name: Install Environment
        if: steps.cache.outputs.cache-hit != 'true'
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: manubot
          environment-file: build/environment.yml
          auto-activate-base: false
          miniforge-version: 'latest'
      - name: Install Manubot AI revision dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pip install git+https://github.com/manubot/manubot@d4242ffa4194e4a13a68c5f6466feff559d3f9d5#egg=manubot[ai-rev]
      - name: Revise manuscript
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AI_EDITOR_LANGUAGE_MODEL: ${{ inputs.model }}
          AI_EDITOR_FILENAMES_TO_REVISE: ${{ inputs.file_names }}
          # More variables can be specified to control the behavior of the model:
          #  https://github.com/manubot/manubot-ai-editor/blob/main/libs/manubot_ai_editor/env_vars.py
        run: manubot ai-revision --content-directory content/
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: 'AI-based revision using ${{ inputs.model }}'
          title: 'AI-based revision using ${{ inputs.model }}'
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          add-paths: |
            content/*.md
          branch: ${{ inputs.branch_name }}
          draft: true
